demo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('', include('orders.urls')),
]

orders/urls.py
from django.urls import path, include
from orders import views
from .api_views import ProductViewSet, OrdersView
#from .api_views import total_products, all_products, ProductViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'products', ProductViewSet, 'product')
urlpatterns = [
    path('hello', views.hello),
    path('view_all', views.ViewAll.as_view()),
    path('managerOrders/<int:manager_id>', views.ManagerViewOrders.as_view(), name='manager-orders'),
    path('managers', views.ManagersViewAll.as_view(), name='managers'),
    path('order/filter=<str:json_dict>', OrdersView),
    #path('api/products/total', total_products),
    #path('api/products/', all_products.as_view(), name='all_products'),
    path('api/', include(router.urls))

]

orders/models.py
from django.db import models

class ClinicManager(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    
class MedicalProduct(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    def __str__(self):
        return self.name
    
class Order(models.Model):
    time = models.DateTimeField()
    status = models.CharField(max_length=10)
    manager = models.ForeignKey(ClinicManager, on_delete=models.CASCADE)
    products = models.ManyToManyField(MedicalProduct, through='OrderItem')
    def __str__(self):
        return f'{self.manager.name} ({self.time})'
    
class OrderItem(models.Model):
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(MedicalProduct, on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.product.name} x({self.quantity})'

orders/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView
from orders.models import ClinicManager, Order
from django.views.generic.list import ListView

def hello(request):
    return HttpResponse('Hello, user!')
class ViewAll(TemplateView):
    template_name = "view_all.html"
    def get_context_data(self, **kwargs):
        context = { "orders": [
        { "time": "Feb. 1, 2022, 10:31 a.m.",
        "status": "Delivered"
        },
        { "time": "Feb. 2, 2022, 2:25 p.m.",
        "status": "Delivered"
        },
        { "time": "Feb. 2, 2022, 8:54 p.m.",
        "status": "Confirmed"
        },
        { "time": "Jan. 3, 2020, 6:01 a.m.",
        "status": "Confirmed"
        }
        ]}
        return context

class ManagerViewOrders(TemplateView):
    template_name = "order_list.html"
    def get_context_data(self, **kwargs):
        manager_id = self.kwargs['manager_id']

        context = super().get_context_data(**kwargs)
        context['order_list'] = Order.objects.filter(manager__pk = manager_id)
        context['manager'] = ClinicManager.objects.get(pk = manager_id)
        return context

class ManagersViewAll(ListView):
    template_name = "manager_list.html"
    model = ClinicManager

templates/manager_list.html
<!doctype html>
<html>
  <head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial scale=1">
    <title>View all orders</title>
  </head>
  <body>
    <h1>Showing all managers</h1>
    <ul>
	
    {% for manager in object_list %}
	  <li>
	    <a href="{% url 'manager-orders' manager.pk %}">
		  {{ manager.name }}
		</a>
		({{ manager.order_set.all | length }})
	  </li>
	{% empty %}
	  <li>No managers yet.</li>
    {% endfor %}
    </ul>
  </body>
</html>

templates/order_list.html
<!doctype html>
<html>
  <head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial scale=1">
    <title>View all orders</title>
  </head>
  <body>
    <h1>Showing all orders by {{ manager.name }}</h1>
    <ul>
	
    {% for order in order_list %}
	  <li>[{{ order.status }}] {{ order.time }}
	    <ul>
		  {% for item in order.orderitem_set.all %}
		    <li>{{ item.quantity }} x {{ item.product.name }}</li>
		  {% endfor %}
		</ul>
	  </li>
	{% empty %}
	  <li>No order yet.</li>
    {% endfor %}
    </ul>
  </body>
</html>

templates/view_all.html
<!doctype html>
<html>
  <head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial scale=1">
    <title>View all orders</title>
  </head>
  <body>
    <h1>Showing all orders</h1>
	<p>Number of orders: {{ orders | length }}</p>
    <ul>
       {% for order in orders %}
	     <li>[{{ order.status }}] {{order.time}}</li>
	   {% endfor %}
    </ul>
  </body>
</html>